### ISSUE TITLE
Job 'inventory' for xxx aborted: Job aborted due to plugin failure (cause=ValueError('not enough values to unpack (expected 2, got 1)'))

### ISSUE THREAD

**Issue by alexanderfefelov** [alexanderfefelov/nav-add-ons#15]
Device:

```
System Name             : 
System Contact          : 
System Location         : 
Ethernet Address        : 00:19:cb:51:df:4f
ZyNOS F/W Version       : V3.80(TS.4) | 10/07/2008
RomRasSize              : 3191378
System up Time          :  5691:29:29 (7a204bc5 ticks)
Bootbase Version        : V3.1 | 03/08/2007
ZyNOS CODE              : RAS Oct  6 2008 17:28:42
Product Model           : GS-4012F
```

nav-add-ons version: 4cddb2f

NAV version: 5.1.2 (Uninett/nav@90d9a11)

```
2021-06-02 09:57:18,350 [ERROR jobs.jobhandler] [inventory 192-168-31-30.internal] Plugin nav.ipdevpoll.plugins.interfaces.Interfaces('192-168-31-30.internal') reported an unhandled failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/interfaces.py", line 56, in handle
    yield df
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/interfaces.py", line 134, in _get_stack_status
    stack = yield self.ifmib.get_stack_status().addCallback(_stackify)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/nav/mibs/if_mib.py", line 96, in get_stack_status
    result = [(h, l) for h, l in status.keys() if h > 0 and l > 0]
  File "/usr/local/lib/python3.7/site-packages/nav/mibs/if_mib.py", line 96, in <listcomp>
    result = [(h, l) for h, l in status.keys() if h > 0 and l > 0]
builtins.ValueError: not enough values to unpack (expected 2, got 1)

2021-06-02 09:57:18,350 [ERROR jobs.jobhandler] [inventory 192-168-31-30.internal] Job 'inventory' for 192-168-31-30.internal aborted: Job aborted due to plugin failure (cause=ValueError('not enough values to unpack (expected 2, got 1)'))
```

**Comment by alexanderfefelov** [comment]
`snmpwalk -c foobar -v 2c [ZyXEL GS-4012F] IF-MIB::ifStackStatus`:

```
IF-MIB::ifStackStatus.1 = INTEGER: active(1)
IF-MIB::ifStackStatus.2 = INTEGER: active(1)
IF-MIB::ifStackStatus.3 = INTEGER: active(1)
IF-MIB::ifStackStatus.4 = INTEGER: active(1)
IF-MIB::ifStackStatus.5 = INTEGER: active(1)
IF-MIB::ifStackStatus.6 = INTEGER: active(1)
IF-MIB::ifStackStatus.7 = INTEGER: active(1)
IF-MIB::ifStackStatus.8 = INTEGER: active(1)
IF-MIB::ifStackStatus.9 = INTEGER: active(1)
IF-MIB::ifStackStatus.10 = INTEGER: active(1)
IF-MIB::ifStackStatus.11 = INTEGER: active(1)
IF-MIB::ifStackStatus.12 = INTEGER: active(1)
IF-MIB::ifStackStatus.10000 = INTEGER: active(1)
```
