### ISSUE TITLE
Job 'inventory' for xxx aborted: Job aborted due to plugin failure (cause=TypeError("'int' object is not iterable"))

### ISSUE THREAD

**Issue by alexanderfefelov** [alexanderfefelov/nav-add-ons#16]
Device:

```
tau-72> show system
TAU-72.IP Rev4
System version: #2.17.0.45
Linux version: #312 Fri Feb 2 14:24:42 NOVT 2018
Firmware version: v10_23_03_15
BPU version: TAU72 PLD v20150928 date: 2015 Sep 28 time 15:51:45
```

nav-add-ons version: 4cddb2f

NAV version: 5.1.2 (Uninett/nav@90d9a11)

```
021-06-03 09:26:13,709 [ERROR jobs.jobhandler] [inventory 192-168-50-17.internal] Plugin nav.ipdevpoll.plugins.juniperdot1q.JuniperDot1q('192-168-50-17.internal') reported an unhandled failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/juniperdot1q.py", line 64, in handle
    yield super(JuniperDot1q, self).handle()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/dot1q.py", line 73, in handle
    yield self._get_tagging_info()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/dot1q.py", line 110, in _get_tagging_info
    egress, untagged = yield self._retrieve_vlan_ports()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/juniperdot1q.py", line 83, in _retrieve_vlan_ports
    (egress, untagged) = yield super(JuniperDot1q, self)._retrieve_vlan_ports()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/dot1q.py", line 119, in _retrieve_vlan_ports
    egress = yield query.get_vlan_current_egress_ports()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/nav/mibs/qbridge_mib.py", line 126, in convert_data_to_portlist
    for key, data in result.items()}
  File "/usr/local/lib/python3.7/site-packages/nav/mibs/qbridge_mib.py", line 126, in <dictcomp>
    for key, data in result.items()}
  File "/usr/local/lib/python3.7/site-packages/nav/mibs/qbridge_mib.py", line 160, in portlist
    return portlist_spec(data)
  File "/usr/local/lib/python3.7/site-packages/nav/mibs/qbridge_mib.py", line 131, in portlist_spec
    vector = nav.bitvector.BitVector(data)
  File "/usr/local/lib/python3.7/site-packages/nav/bitvector.py", line 37, in __init__
    self.vector = array.array("B", octetstring)
builtins.TypeError: 'int' object is not iterable

2021-06-03 09:26:13,709 [ERROR jobs.jobhandler] [inventory 192-168-50-17.internal] Job 'inventory' for 192-168-50-17.internal aborted: Job aborted due to plugin failure (cause=TypeError("'int' object is not iterable"))
```

**Comment by alexanderfefelov** [comment]
`snmpwalk -c foobar -v 2c  [Eltex TAU-72.IP] Q-BRIDGE-MIB::dot1qVlanStaticName`:

```
Q-BRIDGE-MIB::dot1qVlanStaticName.1028164.5 = Wrong Type (should be OCTET STRING): INTEGER: 0
Q-BRIDGE-MIB::dot1qVlanStaticName.1028164.5 = Wrong Type (should be OCTET STRING): INTEGER: 0
Error: OID not increasing: Q-BRIDGE-MIB::dot1qVlanStaticName.1028164.5
 >= Q-BRIDGE-MIB::dot1qVlanStaticName.1028164.5
```

**Comment by alexanderfefelov** [comment]
I will try to patch `mibs/qbridge_mib.py`:

```diff
125,126c125,129
<     return {key: portlist(data, juniper_hack)
<             for key, data in result.items()}
---
>     try:
>         return {key: portlist(data, juniper_hack)
>                 for key, data in result.items()}
>     except TypeError:
>         return {}
```
