### ISSUE TITLE
Job 'topo' for xxx aborted: Job aborted due to plugin failure (cause=ValueError('A string literal cannot contain NUL (0x00) characters.'))

### ISSUE THREAD

**Issue by alexanderfefelov** [alexanderfefelov/nav-add-ons#3]
Device:

```
[admin@MikroTik] > system resource print
             uptime: 13w1d21h53m30s
            version: 6.47 (stable)
         build-time: Jun/02/2020 07:38:00
   factory-software: 6.38.5
        free-memory: 1570.9MiB
       total-memory: 1984.0MiB
                cpu: tilegx
          cpu-count: 9
      cpu-frequency: 1200MHz
           cpu-load: 8%
     free-hdd-space: 75.8MiB
    total-hdd-space: 128.0MiB
  architecture-name: tile
         board-name: CCR1009-7G-1C-1S+
           platform: MikroTik
```

nav-add-ons version: 5afa4fa

NAV version: 5.0.6 (Uninett/nav@36819dfbcab797ec127ad490e5165cfb2285a70a)

`ipdevpolld.log`:

```
2020-09-20 15:40:18,700 [ERROR jobs.jobhandler] [topo 192-168-1-1.internal] Plugin nav.ipdevpoll.plugins.lldp.LLDP('192-168-1-1.internal') reported an unhandled failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 71, in handle
    yield run_in_thread(self._process_remote)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/db.py", line 100, in _reset
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 116, in _process_remote
    neighbors = [LLDPNeighbor(lldp) for lldp in self.remote]
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 116, in <listcomp>
    neighbors = [LLDPNeighbor(lldp) for lldp in self.remote]
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 117, in __init__
    self.identify()
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 120, in identify
    self.netbox = self._identify_netbox()
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 191, in _identify_netbox
    netbox = self._netbox_from_sysname(self.record.sysname)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 180, in _netbox_from_sysname
    return self._netbox_query(query)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 192, in _netbox_query
    netbox = manage.Netbox.objects.values('id', 'sysname').get(query)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 841, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
builtins.ValueError: A string literal cannot contain NUL (0x00) characters.

2020-09-20 15:40:18,701 [ERROR jobs.jobhandler] [topo 192-168-1-1.internal] Job 'topo' for 192-168-1-1.internal aborted: Job aborted due to plugin failure (cause=ValueError('A string literal cannot contain NUL (0x00) characters.'))
2020-09-20 15:40:18,703 [INFO schedule.netboxjobscheduler] [topo 192-168-1-1.internal] topo for 192-168-1-1.internal failed in 0:00:00.458640. next run in 0:06:58.999947.
```

**Comment by alexanderfefelov** [comment]
Looks like #1 (and Uninett/nav#2047, Uninett/nav#2176).

**Comment by alexanderfefelov** [comment]
Device:

```
* 10.254.254.28.1 # show switch

SysName:          10.254.254.28
SysLocation:      
SysContact:       support@extremenetworks.com, +1 888 257 3000
System MAC:       00:04:96:7D:C1:7C
System Type:      X670-48x

SysHealth check:  Enabled (Normal)
Recovery Mode:    All
System Watchdog:  Enabled

Current Time:     Thu Mar 11 10:59:50 2021
Timezone:         [Auto DST Disabled] GMT Offset: 0 minutes, name is UTC.
Boot Time:        Fri Jan 29 14:51:28 2021
Boot Count:       53
Next Reboot:      None scheduled
System UpTime:    40 days 20 hours 8 minutes 22 seconds 

Current State:    OPERATIONAL             
Image Selected:   primary                 
Image Booted:     primary                 
Primary ver:      16.2.4.5                
                  patch1-8
Secondary ver:    16.2.4.5    

Config Selected:  NONE                                                 
Config Booted:    Factory Default
```

nav-add-ons version: 794dfdd

NAV version: 5.1.2 (Uninett/nav@90d9a11)

`ipdevpolld.log`:

```
2021-03-10 20:06:49,307 [ERROR jobs.jobhandler] [topo 10-254-254-28.internal] Plugin nav.ipdevpoll.plugins.lldp.LLDP('10-254-254-28.internal') reported an unhandled failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 85, in handle
    yield run_in_thread(self._process_remote)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/db.py", line 100, in _reset
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 155, in _process_remote
    neighbors = [LLDPNeighbor(lldp) for lldp in self.remote]
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 155, in <listcomp>
    neighbors = [LLDPNeighbor(lldp) for lldp in self.remote]
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 117, in __init__
    self.identify()
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 120, in identify
    self.netbox = self._identify_netbox()
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/plugins/lldp.py", line 230, in _identify_netbox
    netbox = self._netbox_from_sysname(self.record.sysname)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 180, in _netbox_from_sysname
    return self._netbox_query(query)
  File "/usr/local/lib/python3.7/site-packages/nav/ipdevpoll/neighbor.py", line 192, in _netbox_query
    netbox = manage.Netbox.objects.values('id', 'sysname').get(query)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 113, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1094, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
builtins.ValueError: A string literal cannot contain NUL (0x00) characters.

2021-03-10 20:06:49,307 [ERROR jobs.jobhandler] [topo 10-254-254-28.internal] Job 'topo' for 10-254-254-28.internal aborted: Job aborted due to plugin failure (cause=ValueError('A string literal cannot contain NUL (0x00) characters.'))
2021-03-10 20:06:49,307 [INFO schedule.netboxjobscheduler] [topo 10-254-254-28.internal] topo for 10-254-254-28.internal failed in 0:00:52.429736. next run in 0:06:35.999984.
```
